# Generated by Django 6.0.6 on 2026-06-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('avatar_url', models.URLField(blank=True, verbose_name='URL do avatar')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='quizzes.turma')),
            ],
            options={
                'ordering': ('nome',),
                'constraints': [models.UniqueConstraint(fields=('turma', 'nome'), name='nome_aluno_unico_na_turma')],
            },
        ),
    ]
