# Generated by Django 6.0.6 on 2026-06-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_avatar_aluno_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
