"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


def clean_domain(value):
    return value.replace("https://", "", 1).replace("http://", "", 1).strip().rstrip("/") if value else None


DEBUG = env_bool("DEBUG", True)
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured("Defina a variável SECRET_KEY no ambiente de produção.")
    SECRET_KEY = "django-insecure-local-development-only"

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1,testserver")
if render_hostname := os.getenv("RENDER_EXTERNAL_HOSTNAME"):
    ALLOWED_HOSTS.append(render_hostname)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'storages',
    'accounts',
    'quizzes',
    'questions',
    'students',
    'results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if database_url := os.getenv("DATABASE_URL"):
    try:
        import dj_database_url
    except ImportError as exc:
        raise ImproperlyConfigured("Instale dj-database-url para usar DATABASE_URL.") from exc
    # Allow overriding connection age and health checks via environment
    conn_max_age = int(os.getenv("DATABASE_CONN_MAX_AGE", "600"))
    conn_health_checks = env_bool("DATABASE_CONN_HEALTH_CHECKS", True)
    DATABASES = {
        "default": dj_database_url.config(
            default=database_url,
            conn_max_age=conn_max_age,
            conn_health_checks=conn_health_checks,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Rio_Branco'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE_BACKEND = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if not DEBUG
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": STATICFILES_STORAGE_BACKEND},
}

CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS") or [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# If a single FRONTEND_URL is provided, add it to CORS and CSRF trusted origins
FRONTEND_URL = os.getenv("FRONTEND_URL")
if FRONTEND_URL:
    if FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)
    # CSRF_TRUSTED_ORIGINS expects scheme (https://...) entries
    if not CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = []
    if FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

AUTH_USER_MODEL = 'accounts.User'

AUTH_COOKIE_ACCESS = 'quiz_access'
AUTH_COOKIE_REFRESH = 'quiz_refresh'
AUTH_COOKIE_SECURE = not DEBUG

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CookieJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", BASE_DIR / "media"))

# Render encerra TLS no proxy antes de encaminhar a requisição ao Gunicorn.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
X_FRAME_OPTIONS = 'DENY'

# Avoid automatic redirecting of URLs with/without trailing slash.
# Vercel may normalize trailing slashes when proxying; disabling APPEND_SLASH
# prevents POST requests from being redirected and losing their payload.
APPEND_SLASH = False

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}


# Cloud / Media storage (Cloudflare R2 / S3-compatible)
# Use local filesystem by default; in production set USE_CLOUDFLARE_R2=true
USE_CLOUDFLARE_R2 = env_bool("USE_CLOUDFLARE_R2", False)
R2_ENDPOINT = os.getenv("R2_ENDPOINT")  # e.g. https://<account>.r2.cloudflarestorage.com
R2_BUCKET = os.getenv("R2_BUCKET")  # e.g. quiz-kids
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION") or os.getenv("AWS_S3_REGION_NAME") or "auto"
AWS_S3_SIGNATURE_VERSION = os.getenv("AWS_S3_SIGNATURE_VERSION", "s3v4")
AWS_S3_CUSTOM_DOMAIN = clean_domain(os.getenv("AWS_S3_CUSTOM_DOMAIN"))
AWS_LOCATION = os.getenv("AWS_LOCATION", "").strip("/")
AWS_QUERYSTRING_AUTH = env_bool("AWS_QUERYSTRING_AUTH", False)
USE_REMOTE_MEDIA_STORAGE = USE_CLOUDFLARE_R2 or bool(R2_ENDPOINT and R2_BUCKET)

if USE_REMOTE_MEDIA_STORAGE:
    if not R2_ENDPOINT:
        raise ImproperlyConfigured("Defina R2_ENDPOINT para usar Cloudflare R2.")
    if not R2_BUCKET:
        raise ImproperlyConfigured("Defina R2_BUCKET para usar Cloudflare R2.")
    if not AWS_ACCESS_KEY_ID:
        raise ImproperlyConfigured("Defina AWS_ACCESS_KEY_ID para usar Cloudflare R2.")
    if not AWS_SECRET_ACCESS_KEY:
        raise ImproperlyConfigured("Defina AWS_SECRET_ACCESS_KEY para usar Cloudflare R2.")

    AWS_STORAGE_BUCKET_NAME = R2_BUCKET
    AWS_S3_ENDPOINT_URL = R2_ENDPOINT
    AWS_S3_ADDRESSING_STYLE = os.getenv("AWS_S3_ADDRESSING_STYLE", "path")
    AWS_DEFAULT_ACL = os.getenv("AWS_DEFAULT_ACL") or None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': os.getenv('AWS_S3_CACHE_CONTROL', 'max-age=86400'),
    }

    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    }

    if AWS_S3_CUSTOM_DOMAIN:
        media_prefix = f"{AWS_LOCATION}/" if AWS_LOCATION else ""
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN.rstrip('/')}/{media_prefix}"

