# Generated by Django 6.0.6 on 2026-06-23 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50, verbose_name='série')),
                ('nome', models.CharField(help_text='Ex.: A, B ou Turma Azul', max_length=50)),
                ('ano_letivo', models.PositiveSmallIntegerField()),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-ano_letivo', 'serie', 'nome'),
                'constraints': [models.UniqueConstraint(fields=('serie', 'nome', 'ano_letivo'), name='turma_unica_por_ano')],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('tempo_limite_segundos', models.PositiveIntegerField(help_text='Tempo total para concluir o quiz.', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantidade_perguntas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pontos_por_acerto', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='quizzes.categoria')),
                ('turma', models.ForeignKey(blank=True, help_text='Deixe vazio para disponibilizar o quiz a qualquer turma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quizzes.turma')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
                'ordering': ('-criado_em',),
            },
        ),
    ]
