# Generated by Django 6.0.6 on 2026-06-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='embaralhar_perguntas',
            field=models.BooleanField(default=True, help_text='Sorteia as perguntas sem repetição a cada nova rodada.'),
        ),
    ]
