databases:
  - name: quizmestrekids-db
    plan: free
    databaseName: quizmestrekids
    user: quizmestrekids

services:
  - type: web
    name: quizmestrekids-api
    runtime: python
    plan: starter
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quizmestrekids-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: USE_CLOUDFLARE_R2
        value: "True"
      - key: R2_ENDPOINT
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_REGION
        value: auto
      - key: AWS_S3_ADDRESSING_STYLE
        value: path
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false
      - key: AWS_LOCATION
        value: ""
      - key: AWS_QUERYSTRING_AUTH
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: WEB_CONCURRENCY
        value: "4"
