# Generated by Django 6.0.6 on 2026-06-23 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='matéria')),
            ],
            options={
                'verbose_name': 'matéria',
                'verbose_name_plural': 'matérias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('nivel', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perguntas', to='questions.materia', verbose_name='matéria')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='quizzes.quiz')),
            ],
            options={
                'ordering': ('quiz', 'ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questions.pergunta')),
            ],
            options={
                'ordering': ('pergunta', 'ordem', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.UniqueConstraint(fields=('quiz', 'ordem'), name='ordem_pergunta_unica_no_quiz'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(fields=('pergunta', 'ordem'), name='ordem_alternativa_unica_na_pergunta'),
        ),
        migrations.AddConstraint(
            model_name='alternativa',
            constraint=models.UniqueConstraint(condition=models.Q(('correta', True)), fields=('pergunta',), name='apenas_uma_alternativa_correta'),
        ),
    ]
