# Generated by Django 6.0.6 on 2026-06-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pergunta_imagens/', verbose_name='imagem'),
        ),
    ]
